version: '3'

services:
  build_env:
    container_name: 'asoul-guide-build-env'
    image: avimitin/asoul-guide-build-env:latest
    hostname: 'asoul-guide-host'
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
